### ISSUE TITLE
访问/db后，页面存在问题

### ISSUE THREAD

**Issue by ZzUbNnn** [Cocowwy/ShowDB#1]
![image](https://user-images.githubusercontent.com/72975752/165502109-e832ec94-fc20-4540-92cb-dc68a871da1e.png)
我不知道是不是我操作的问题，首先代码肯定没有报错 ，使用的是snapshot版本， 添加了repositories

**Comment by ZzUbNnn** [comment]
chrome浏览器

**Comment by Cocowwy** [comment]
有开VPN 之类的吗  因为前端页面使用的是 cdn  样式问题应该是网络问题

**Comment by Cocowwy** [comment]
> ![image](https://user-images.githubusercontent.com/72975752/165502109-e832ec94-fc20-4540-92cb-dc68a871da1e.png) 我不知道是不是我操作的问题，首先代码肯定没有报错 ，使用的是snapshot版本， 添加了repositories

有开VPN 之类的吗 因为前端页面使用的是 cdn 样式问题应该是网络问题

**Comment by Cocowwy** [comment]
> > ![image](https://user-images.githubusercontent.com/72975752/165502109-e832ec94-fc20-4540-92cb-dc68a871da1e.png) 我不知道是不是我操作的问题，首先代码肯定没有报错 ，使用的是snapshot版本， 添加了repositories
> 
> 有开VPN 之类的吗 因为前端页面使用的是 cdn 样式问题应该是网络问题

可以用RELEASE版本的哈

**Comment by ZzUbNnn** [comment]
好像还是不行，请问用了springsecurity后需要放入哪些文件呢

**Comment by Cocowwy** [comment]
> 好像还是不行，请问用了springsecurity后需要放入哪些文件呢

这个一般是网络问题，vue和elementui的cdn没拉下来
/db （页面）和  /showdb/* （相关接口）  相关的的接口放开就行

**Comment by li7hai26** [comment]
确实是网络问题，但是最好还是将这些静态资源打包到项目中，内网环境，没有外网关连接
另外是不是还不支持ORACLE呀

**Comment by Cocowwy** [comment]
> 

当初使用cdn引入 考虑的是节省引入的包的内存大小   这样的话  下个版本我把它打包进去吧
暂时还没写ORACLE哈 TAT

**Comment by Cocowwy** [comment]
> 确实是网络问题，但是最好还是将这些静态资源打包到项目中，内网环境，没有外网关连接 另外是不是还不支持ORACLE呀

当初使用cdn引入 考虑的是节省引入的包的内存大小 这样的话 下个版本我把它打包进去吧
暂时还没写ORACLE哈 TAT

**Comment by Cocowwy** [comment]
vue的脚本已经从cdn迁移至静态目录了  在1.0.1的快照里面
