### ISSUE TITLE
项目这么优秀，可否提供个示例项目？

### ISSUE THREAD

**Issue by bitlin** [Cocowwy/ShowDB#2]
比如基于大名鼎鼎的[若依开源系统](https://github.com/yangzongzhuan/RuoYi-Vue) ，提供下示例

**Comment by Cocowwy** [comment]
> 比如基于大名鼎鼎的[若依开源系统](https://github.com/yangzongzhuan/RuoYi-Vue) ，提供下示例

有示例的哈，在这个模块下有
[showdb-test](https://github.com/Cocowwy/ShowDB/tree/v1-dev/showdb-test)
如果需要看项目预览的话，我晚点部一个公网的demo吧

**Comment by Jiiiiiin** [comment]
的确优秀 支持一下
