### ISSUE TITLE
前端界面启动之后 会报一个 undefined

### ISSUE THREAD

**Issue by Jiiiiiin** [Cocowwy/ShowDB#3]
我使用最小化配置，无头像、email 等诉求（建议这个不需要花费太多力气），访问之后如下：

![Xnip2023-02-19_17-34-23](https://user-images.githubusercontent.com/8840636/219940268-be3e5194-4d48-46c1-bb8e-3832ad02830a.jpg)

配置如下：

```properties
showdb.enable=true
showdb.refresh=500
#showdb.plugin.generate=true
```

springboot-version 2.7.3

**Comment by Cocowwy** [comment]
好的 了解  我会在下个最新的稳定版/或者最近的一次快照版 将这些配置移除～

**Comment by Cocowwy** [comment]
> 我使用最小化配置，无头像、email 等诉求（建议这个不需要花费太多力气），访问之后如下：
> 
> ![Xnip2023-02-19_17-34-23](https://user-images.githubusercontent.com/8840636/219940268-be3e5194-4d48-46c1-bb8e-3832ad02830a.jpg)
> 
> 配置如下：
> 
> ```ini
> showdb.enable=true
> showdb.refresh=500
> #showdb.plugin.generate=true
> ```
> 
> springboot-version 2.7.3

好的 了解 我会在下个最新的稳定版/或者最近的一次快照版 将这些配置移除～

**Comment by Cocowwy** [comment]
> 我使用最小化配置，无头像、email 等诉求（建议这个不需要花费太多力气），访问之后如下：
> 
> ![Xnip2023-02-19_17-34-23](https://user-images.githubusercontent.com/8840636/219940268-be3e5194-4d48-46c1-bb8e-3832ad02830a.jpg)
> 
> 配置如下：
> 
> ```ini
> showdb.enable=true
> showdb.refresh=500
> #showdb.plugin.generate=true
> ```
> 
> springboot-version 2.7.3

可以先试试这个版本 1.1.2-SNAPSHOT

**Comment by Cocowwy** [comment]
> 我使用最小化配置，无头像、email 等诉求（建议这个不需要花费太多力气），访问之后如下：
> 
> ![Xnip2023-02-19_17-34-23](https://user-images.githubusercontent.com/8840636/219940268-be3e5194-4d48-46c1-bb8e-3832ad02830a.jpg)
> 
> 配置如下：
> 
> ```ini
> showdb.enable=true
> showdb.refresh=500
> #showdb.plugin.generate=true
> ```
> 
> springboot-version 2.7.3

1.1.2  可以直接使用这个版本，文档已更新😙

**Comment by Jiiiiiin** [comment]
@Cocowwy 好的 谢谢，另外建议 左侧图标 不用这么大（区域），要上升到企业级，把功夫花在 数据库展示 调优上 谢谢

**Comment by Cocowwy** [comment]
> @Cocowwy 好的 谢谢，另外建议 左侧图标 不用这么大（区域），要上升到企业级，把功夫花在 数据库展示 调优上 谢谢

了解～。已经删除了哈哈，这些还在慢慢的优化中...
